<?php
    $form = new PexAdmin_Form();

    /** @var Model_PermissionsEntity $oPlayer */
    $oPlayer = $this->oPlayer;
    $parents = $this->parents;

    $isCreate = empty($oPlayer->getId());

    $requiredStar = '<span class="text-danger">*</span>';

    $parents = (!$isCreate && isset($this->parents[$oPlayer->getName()]))
        ? $this->parents[$oPlayer->getName()]
        : []
    ;

    $options = $oPlayer->getOptions();

    $username = isset($options['']['name'])
        ? $options['']['name']
        : ''
    ;

    $optionIdentifier = 1;

    $playerUuid = $oPlayer->getName();

    $canCreate = PexAdmin_Acl::isAllowed('PLAYER', 'CREATE');
    $canEdit = PexAdmin_Acl::isAllowed('PLAYER', 'UPDATE');
    $canDelete = PexAdmin_Acl::isAllowed('PLAYER', 'DELETE');
?>
<form method="post">
	<input type="hidden" id="options[0][name]" name="options[0][name]" value="name">
	<input type="hidden" id="options[0][world]" name="options[0][world]" value="">
    <?php
        echo $form->getInput('name', 'text', [
            'caption' => 'Player UUID'.($isCreate ? $requiredStar : ''),
            'value' => $playerUuid,
            'readonly' => !$isCreate,
            'required' => $isCreate,
        ]);

        echo $form->getInput('options[0][value]', 'text', [
            'caption' => 'Player Name (last seen)'.($canEdit ? $requiredStar : ''),
            'value' => $username,
            'required' => true,
            'readonly' => !$canEdit
        ]);

        $parentsOptions = array();
        foreach ($parents as $parent)
        {
            $parentsOptions[] = [
                'value' => $parent,
                'caption' => $parent,
                'selected' => 'selected'
            ];
        }

        echo $form->getAjaxSelect(
            'parents',
            Oxygen_Utils::url('group-list-ajax'),
            $parentsOptions,
            array(
                'name' => 'parents[]',
                'multiple' => 'multiple',
                'caption' => 'Inherit permissions from these groups',
                'placeholder' => 'Select one or more group',
                'disabled' => !$canEdit
            )
        );
    ?>

	<hr/>
	<h4>Options</h4>
    <div id="options">
	<?php foreach ($options as $worldName => $worldData)
	{

        foreach ($worldData as $optionName => $optionValue)
        {
            if ($worldName == '' && $optionName == 'name')
                continue;
            ?>
    		<div class="input-group">
        		<span class="input-group-addon">
        			<?= $form->getInput('options['.$optionIdentifier.'][name]', 'text', [
                        'placeholder' => 'Option name',
                        'value' => $optionName,
    			        'readonly' => !$canEdit
                    ]); ?>
                </span>
        		<span class="input-group-addon">
        			<?= $form->getInput('options['.$optionIdentifier.'][value]', 'text', [
                        'placeholder' => 'Option value*',
                        'value' => $optionValue,
                        'required' => true,
    			        'readonly' => !$canEdit
                    ]); ?>
                </span>
        		<span class="input-group-addon">
        			<?= $form->getInput('options['.$optionIdentifier.'][world]', 'text', [
                        'placeholder' => 'World (leave blank for global)',
                        'value' => $worldName,
    			        'readonly' => !$canEdit
                    ]); ?>
                </span>
                <?php if ($canEdit) { ?>
                <span class="input-group-addon">
                    <button type="button" class="btn btn-default remove-option" aria-label="Remove">
                    	<span class="fa fa-trash fa-lg" aria-hidden="true"></span>
                    </button>
                </span>
                <?php } ?>
            </div>
        	<?php
        	$optionIdentifier++;
        }
    }
    ?>
    </div>

	<br/>

   <?= ($canEdit)
        ? $form->getButton(
            'Add one more',
            'addOption()',
            array(
                'class' => 'btn-default'
            )
        )
        : ''
    ?>

    <br/>

    <br/>

    <div class="box-footer">
        <?php

        if ($canEdit)
        {
            echo $form->getSubmitButton(
                'Save',
                array(
                    'class' => 'btn-primary'
                )
            );
        }

        if (!$isCreate)
        {
            if ($canCreate)
            {
                echo ' ';
                echo $form->getButton(
                    'Clone',
                    'duplicate()',
                    array(
                        'id' => 'clone',
                        'class' => 'btn-success',
                    )
                );
            }

            echo ' <img class="loader" style="display:none" src="'.$this->basedir.'/assets/img/loader.gif"/>';

            echo $form->getButton(
                'Go to player permissions',
                'window.location = "'.Oxygen_Utils::url('permission-edit', [
                    'name' => urlencode($oPlayer->getName()),
                    'type' => Model_Permission::TYPE_PLAYER
                ]).'"',
                array(
                    'class' => 'btn-secondary',
                )
            );

            if ($canDelete)
            {
                echo $form->getButton(
                    'Remove',
                    'remove()',
                    array(
                        'class' => 'btn-danger pull-right',
                    )
                );
            }
        }
        ?>
    </div>
</form>

<?php if ($canEdit) { ?>
<script>
	var optionPrototype = `
		<div class="input-group">
    		<span class="input-group-addon">
    			<?= $form->getInput('options[__OPTION_ID__][name]', 'text', [
                    'placeholder' => 'Option name*',
                    'value' => '',
                    'required' => true
                ]); ?>
            </span>
    		<span class="input-group-addon">
    			<?= $form->getInput('options[__OPTION_ID__][value]', 'text', [
                    'placeholder' => 'Option value*',
                    'value' => '',
                    'required' => true
                ]); ?>
            </span>
    		<span class="input-group-addon">
    			<?= $form->getInput('options[__OPTION_ID__][world]', 'text', [
                    'placeholder' => 'World (leave blank for global)',
                    'value' => ''
                ]); ?>
            </span>
            <span class="input-group-addon">
                <button type="button" class="btn btn-default remove-option" aria-label="Remove">
                	<span class="fa fa-trash fa-lg" aria-hidden="true"></span>
                </button>
            </span>
        </div>
	`;

	var optionId = <?= $optionIdentifier ?>;

	$('.remove-option').click(function() {
		$(this).parent().parent().remove();
	});

	function addOption()
	{
		var optionContent = optionPrototype.replace(/__OPTION_ID__/g, optionId);

		optionId++;

		$('#options').append(optionContent);

		$('.remove-option').click(function() {
			$(this).parent().parent().remove();
		});
	}

	function remove()
	{
		if (confirm('Are you sure you want to remove this player ?'))
		{
			$('.loader').show();
			$.post('<?= Oxygen_Utils::url('player-delete') ?>',
			{
				name: $('#name').val()
			},
			function (data) {
				if (data == '')
					document.location = '<?= Oxygen_Utils::url('player-index') ?>';
				else
				{
					alert(data);
					$('.loader').hide();
				}
			});
		}
	}

	function duplicate()
	{
	    var name = prompt("       Please enter the cloned player UUID       ", '');

        if (name != null && name!='')
        {
        	$('.loader').show();

			$.post('<?= Oxygen_Utils::url('player-clone') ?>',
			{
				name: $('#name').val(),
				newName: name
			},
			function (data) {
				if (data == '')
					document.location = '<?= Oxygen_Utils::url('player-edit') ?>'+name;
				else
				{
					alert(data);
					$('.loader').hide();
				}
			});
        }
	}
</script>
<?php } ?>