<?php
    $form = new PexAdmin_Form();
?>
<link rel="stylesheet" href="<?= $this->basedir ?>/assets/lib/datatables/dataTables.bootstrap.css">

<div id="players-table-container">
    <table id="players-table" class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Player UUID</th>
                <th>Global options</th>
                <th>Assigned groups</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
        <tfoot>
            <tr>
                <th>Player UUID</th>
                <th>Global options</th>
                <th>Assigned groups</th>
            </tr>
        </tfoot>
    </table>
</div>

<?php

if (PexAdmin_Acl::isAllowed('PLAYER', 'CREATE'))
{
    echo $form->getButton(
        'Add a new player',
        'window.location = "'.Oxygen_Utils::url('player-edit').'"',
        ['class' => 'btn-primary']
    );
}
?>

<script src="<?= $this->basedir ?>/assets/lib/datatables/jquery.dataTables.min.js"></script>
<script src="<?= $this->basedir ?>/assets/lib/datatables/dataTables.bootstrap.min.js"></script>

<script>
$(function() {
    $('#players-table').on('init.dt', function(e, settings, json) {
        $('#players-table-container select').select2({
            theme: "bootstrap"
        });
    }).DataTable({
      "paging": true,
      "pageLength": 25,
      "ordering": true,
      "searching": true,
      "responsive": true,
      "processing": true,
      "serverSide": true,
      "ajax": "<?= Oxygen_Utils::url('player-list') ?>",
      "columnDefs": [
        { "orderable": false, "targets": [1, 2] }
      ]
    });
});
</script>