<!DOCTYPE html>
<html>
    <head>
        <title>PermissionsEx Administration</title>

        <link rel="stylesheet" type="text/css" href="<?= $this->basedir ?>/assets/lib/font-awesome/css/font-awesome.min.css">

        <link rel="stylesheet" type="text/css" href="<?= $this->basedir ?>/assets/lib/bootstrap/css/bootstrap.css">

        <link rel="stylesheet" type="text/css" href="<?= $this->basedir ?>/assets/lib/select2/select2.min.css">
        <link rel="stylesheet" type="text/css" href="<?= $this->basedir ?>/assets/lib/select2/select2-bootstrap.min.css">

        <link rel="stylesheet" type="text/css" href="<?= $this->basedir ?>/assets/lib/switchery/switchery.css">
        <link rel="stylesheet" type="text/css" href="<?= $this->basedir ?>/assets/css/design.css">

        <script src="<?= $this->basedir ?>/assets/lib/jquery.js"></script>
    </head>
    <body>
    	<?= Oxygen_Auth::getIdentity()
    	   ? $this->partial('layout/menu.phtml', ['toolbarCurrent' => $this->toolbarCurrent])
    	   : ''
    	?>

        <div id="content">
            <?= !empty($this->title) ? '<h2>'.$this->title.'</h2>' : '' ?>
            <?= $this->_content ?>
        </div>

        <script type="text/javascript" src="<?= $this->basedir ?>/assets/lib/bootstrap/js/bootstrap.js"></script>
        <script type="text/javascript" src="<?= $this->basedir ?>/assets/lib/select2/select2.min.js"></script>
        <script type="text/javascript" src="<?= $this->basedir ?>/assets/lib/switchery/switchery.js"></script>
    </body>
</html>