<?php
    $identity = Oxygen_Auth::getIdentity();
    $login = $identity['login'];
?>
<nav class="navbar navbar-default navbar-static-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="<?= $this->basedir ?>/">PEXAdmin</a>
            </div>
            <ul class="nav navbar-nav">
            <?= $this->toolbar(array(
                'groups' => array(
                    'title' => 'Groups',
                    'link' => Oxygen_Utils::url('group-index')
                ),
                "players" => array(
                    'title' => 'Players',
                    'link' => Oxygen_Utils::url('player-index')
                ),
                "permissions" => array(
                    'title' => 'Permissions',
                    'link' => Oxygen_Utils::url('permission-index')
                ),
                "logout" => array(
                    'title' => 'Logout ['.ucfirst($login).']',
                    'link' => Oxygen_Utils::url('logout')
                ),
            ), $this->toolbarCurrent)
            ?>
        </ul>
    </div>
</nav>